# Generated by Django 2.2.5 on 2020-04-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=200)),
                ('game_price', models.IntegerField()),
                ('game_size', models.IntegerField()),
                ('game_genre', models.CharField(choices=[('ACT', 'Action'), ('ANM', 'Anime'), ('2v2', '2 vs 2')], max_length=3)),
                ('game_min_graphics', models.IntegerField()),
                ('game_short_description', models.CharField(max_length=500)),
            ],
        ),
    ]
